<?php $name =  $this->getRequest()->getParam('fname').' '.$this->getRequest()->getParam('lname'); ?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo 'Thank You Form' ?></h3></td>
        </tr>
    </table>
</div>

<div style="background-color:#fafafa;">
<p>Hi <?php echo $name; ?>,</p><br>

<p>Thank you for submitting your request. A representative from Thylaksoft will contact you shortly to discuss your needs.</p><br> <p>If you need to talk to someone right away, please call us at 302-355-0449.</p><br>

<p>Thanks,</p><br>
<p>Thylaksoft LLC. </p>
</div>
<!--<div class="form-buttons" align="right"><a href="" title="Back">Back</a></div>-->
